### ISSUE TITLE
How do you convert the packets into an usable format?

### ISSUE THREAD

**Issue by joojoooo** [WorldDownloader/WorldDownloader#1]

**Comment by vibezjit** [comment]
> _No description provided._

Hey it seems like you got it to work.. You think you can tell me how to actually use this WorldDownloader because the instructions make no sense to a newbie like me. Thanks!

**Comment by joojoooo** [comment]
No, I made my own world downloader, I don't think the code here still works for newer versions, even if it does I have no idea how you compile and use it. I was just wondering if they made a tool to convert the packets into leveldb. But no answer so I made my own converter too. If you need to download some worlds contact me on discord @jojojo#8529

**Comment by joojoooo** [comment]
@vibezjit btw, the software is private and not for sale

**Comment by vibezjit** [comment]
> No, I made my own world downloader, I don't think the code here still works for newer versions, even if it does I have no idea how you compile and use it. I was just wondering if they made a tool to convert the packets into leveldb. But no answer so I made my own converter too. If you need to download some worlds contact me on discord @jojojo#8529

Hey I sent you a friend request on discord from saved#3217 and thanks for offering to help
